@host = http://localhost:5213
@hostId = abcd

POST  {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZDRhNzAzNS1hNWIwLTRmMTMtODcwZS05NGExYjdjZjZkYzUiLCJnaXZlbl9uYW1lIjoiVmVkaWthIiwiZmFtaWx5X25hbWUiOiJHdWphciIsImp0aSI6ImJmNWYyNDdlLWJmNGEtNDU0OS1iNDcyLWNmYjgyYzk5MTM5YSIsImV4cCI6MTY4OTIzOTU3NSwiaXNzIjoiQnViYmVyRGlubmVyIiwiYXVkIjoiQnViYmVyRGlubmVyIn0.ihta3t6LQWtZmB4SB_Wigw4HdehgRnNzz5wrWFww5UU

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "averageRating": 4.5,
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ],
    "hostId": { "value": "00000000-0000-0000-0000-000000000000" },
    "dinnerIds": [
        { "value": "00000000-0000-0000-0000-000000000000" }
    ],
    "menuReviewIds": [
        { "value": "00000000-0000-0000-0000-000000000000" }
    ],
    "createdDateTime": "2020-01-01T00:00:00.0000000Z",
    "updatedDateTime": "2020-01-01T00:00:00.0000000Z"
}