@host = http://localhost:5213

GET {{host}}/dinners
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNWVhMWZhZC1mYTc4LTQ4ZDctOGQ1Ny0wNmQyZTU0YTc1YzYiLCJnaXZlbl9uYW1lIjoiVmVkaWthIiwiZmFtaWx5X25hbWUiOiJHdWphciIsImp0aSI6IjRlYmE0NzgzLWQ3MDYtNDkwYS1hNjdjLTg2MDY5NGVmZGEyZCIsImV4cCI6MTY4OTE0ODY1OSwiaXNzIjoiQnViYmVyRGlubmVyIiwiYXVkIjoiQnViYmVyRGlubmVyIn0.JZRT4_cquMhQK1aVUDDO0qFFDap2T9cljYtp1rN0iHM

