@host = http://localhost:5213

GET {{host}}/dinners
Authorization:  "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNWVhMWZhZC1mYTc4LTQ4ZDctOGQ1Ny0wNmQyZTU0YTc1YzYiLCJnaXZlbl9uYW1lIjoiVmVkaWthIiwiZmFtaWx5X25hbWUiOiJHdWphciIsImp0aSI6IjRjZjgzYTlmLWZjZDYtNDViYi1iZWYzLTAzMmFlOGQ1MmRjOSIsImV4cCI6MTY4OTE0ODUxMiwiaXNzIjoiQnViYmVyRGlubmVyIiwiYXVkIjoiQnViYmVyRGlubmVyIn0.tXMrOoEqM3gxgjKDxf8PCX4tcfCcozl01kUuoW5vb20"

